version: 2.1

environment: &environment
  LOG_LEVEL: WARN

jobs:
  run_cops:
    working_directory: ~/repos/africansms

    docker:
      - image: circleci/ruby:2.6.4-buster-node
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: check dependencies
          command: |
            gem install bundler:2.2.23
            bundle -v
            bundle exec ruby -v

      - run:
          name: install gems
          command: bundle install && bundle clean

      - run:
          name: run rubocop
          command: rubocop

  publish_to_rubygems:
    working_directory: ~/repos/africansms

    docker:
      - image: circleci/ruby:2.6.4-buster-node
        environment:
          <<: *environment

    steps:
      - checkout

      - run:
          name: setup Rubygems
          command: bash .circleci/setup-rubygems.sh

      - run:
          name: publish to Rubygems
          command: |
            gem build africansms.gemspec
            gem push "africansms-$(git describe --tags).gem"

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_cops
      - publish_to_rubygems:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
